### ISSUE TITLE
PHPCrawlerUtils class appears twice in the libs folder

### ISSUE THREAD

**Issue by Deadlyforce** [mmerian/phpcrawl#1]
...and when autoloading the classes the wrong one is loaded (the one missing some of the methods used by the script). PHPCrawlerUtils appears in libs/Utils (the right one) but also in libs/.

**Comment by mmerian** [comment]
Hi,

Thanks for this report. I've just fixed this in commit e8b4a58. This commit just updated composer.json to ensure the right version of the file is loaded.

Cheers

**Comment by kissifrot** [comment]
Sorry to reopen this issue but it's not really fixed, we now get the warning

>Warning: Ambiguous class resolution, "PHPCrawlerUtils" was found in both "(path)/vendor/mmeria /phpcrawl/libs/Utils/PHPCrawlerUtils.class.php" and "(path)/vendor/mmerian/phpcrawl/libs/PHPCrawlerUtils.class.php", the first will be used.

**Comment by mmerian** [comment]
Hi,

Sorry to answer so late. I'll commit a fix for this as soon as possible. In the meantime, you can ignore this warning. It means that composer found two classes with the same name, and that only the first of them will be used.

**Comment by mmerian** [comment]
Hi,

I've commited a fix (69023880e1fcec97d8968de4d540f1bee30f7b76) for this. I removed the useless file from the git index, and also added it to .gitignore, so it won't bother where upgrading from upstream.

This should fix the warning.

**Comment by kissifrot** [comment]
Thanks!

I just hope it'll also be fixed in upstream too.

**Comment by melkawakibi** [comment]
It's been almost two years since the last comment. But people still use your awesome lib. 

I'm trying to set the obeyRobotsTxt but it uses the wrong PHPCrawlerUtils. obeyRobotsTxt calls PHPCrawlerRobotsTxtParser::parseRobotsTxt which in turn calls PHPCrawlerUtils::getURIContent but it doesn't find it, reason why is because it uses this Class:

> vendor/mmerian/phpcrawl/libs/PHPCrawlerUtils.class.php //Doesn't contain getURIContent

Instead of this one, which it should use.

> vendor/mmerian/phpcrawl/libs/Utils/PHPCrawlerUtils.class.php ////Does contain getURIContent

error:

> Call to undefined method PHPCrawlerUtils::getURIContent()

autoload warning:

Warning: Ambiguous class resolution, "PHPCrawlerUtils" was found in both "/Users/macmini2/securityscan/vendor/mmerian/phpcrawl/libs/PHPCrawlerUtils.class.php" and "/Users/macmini2/securityscan/vendor/mmerian/phpcrawl/libs/Utils/PHPCrawlerUtils.class.php", the first will be used.
